<?php

namespace ContainerHAyQvpA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_98k5IshService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.98k5Ish' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin6Controller::dashboard' => ['privates', '.service_locator.n_IEkrD', 'get_ServiceLocator_NIEkrDService', true],
            'App\\Controller\\ApiController::zones' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\DashboardIntelligentController::compareZones' => ['privates', '.service_locator.i8XBfmZ', 'get_ServiceLocator_I8XBfmZService', true],
            'App\\Controller\\DashboardIntelligentController::index' => ['privates', '.service_locator.OluOONX', 'get_ServiceLocator_OluOONXService', true],
            'App\\Controller\\IndicateurImpactController::delete' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController::edit' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController::index' => ['privates', '.service_locator.qAlMOrK', 'get_ServiceLocator_QAlMOrKService', true],
            'App\\Controller\\IndicateurImpactController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\IndicateurImpactController::show' => ['privates', '.service_locator.cP0vxgj', 'get_ServiceLocator_CP0vxgjService', true],
            'App\\Controller\\MapController::index' => ['privates', '.service_locator.GXvkjJ0', 'get_ServiceLocator_GXvkjJ0Service', true],
            'App\\Controller\\QRDashboardController::index' => ['privates', '.service_locator.F1RPxoi', 'get_ServiceLocator_F1RPxoiService', true],
            'App\\Controller\\QRScanController::track' => ['privates', '.service_locator.ivMCWw3', 'get_ServiceLocator_IvMCWw3Service', true],
            'App\\Controller\\ZonePollueeController::batchQR' => ['privates', '.service_locator.dcaf6uT', 'get_ServiceLocator_Dcaf6uTService', true],
            'App\\Controller\\ZonePollueeController::delete' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController::downloadQRPNG' => ['privates', '.service_locator.TwHtLwH', 'get_ServiceLocator_TwHtLwHService', true],
            'App\\Controller\\ZonePollueeController::edit' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController::index' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\ZonePollueeController::new' => ['privates', '.service_locator.wdczQ9j', 'get_ServiceLocator_WdczQ9jService', true],
            'App\\Controller\\ZonePollueeController::show' => ['privates', '.service_locator.R2zCFxk', 'get_ServiceLocator_R2zCFxkService', true],
            'App\\Controller\\ZonePollueeController::showQR' => ['privates', '.service_locator.TwHtLwH', 'get_ServiceLocator_TwHtLwHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin6Controller:dashboard' => ['privates', '.service_locator.n_IEkrD', 'get_ServiceLocator_NIEkrDService', true],
            'App\\Controller\\ApiController:zones' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\DashboardIntelligentController:compareZones' => ['privates', '.service_locator.i8XBfmZ', 'get_ServiceLocator_I8XBfmZService', true],
            'App\\Controller\\DashboardIntelligentController:index' => ['privates', '.service_locator.OluOONX', 'get_ServiceLocator_OluOONXService', true],
            'App\\Controller\\IndicateurImpactController:delete' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController:edit' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController:index' => ['privates', '.service_locator.qAlMOrK', 'get_ServiceLocator_QAlMOrKService', true],
            'App\\Controller\\IndicateurImpactController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\IndicateurImpactController:show' => ['privates', '.service_locator.cP0vxgj', 'get_ServiceLocator_CP0vxgjService', true],
            'App\\Controller\\MapController:index' => ['privates', '.service_locator.GXvkjJ0', 'get_ServiceLocator_GXvkjJ0Service', true],
            'App\\Controller\\QRDashboardController:index' => ['privates', '.service_locator.F1RPxoi', 'get_ServiceLocator_F1RPxoiService', true],
            'App\\Controller\\QRScanController:track' => ['privates', '.service_locator.ivMCWw3', 'get_ServiceLocator_IvMCWw3Service', true],
            'App\\Controller\\ZonePollueeController:batchQR' => ['privates', '.service_locator.dcaf6uT', 'get_ServiceLocator_Dcaf6uTService', true],
            'App\\Controller\\ZonePollueeController:delete' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController:downloadQRPNG' => ['privates', '.service_locator.TwHtLwH', 'get_ServiceLocator_TwHtLwHService', true],
            'App\\Controller\\ZonePollueeController:edit' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController:index' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\ZonePollueeController:new' => ['privates', '.service_locator.wdczQ9j', 'get_ServiceLocator_WdczQ9jService', true],
            'App\\Controller\\ZonePollueeController:show' => ['privates', '.service_locator.R2zCFxk', 'get_ServiceLocator_R2zCFxkService', true],
            'App\\Controller\\ZonePollueeController:showQR' => ['privates', '.service_locator.TwHtLwH', 'get_ServiceLocator_TwHtLwHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin6Controller::dashboard' => '?',
            'App\\Controller\\ApiController::zones' => '?',
            'App\\Controller\\DashboardIntelligentController::compareZones' => '?',
            'App\\Controller\\DashboardIntelligentController::index' => '?',
            'App\\Controller\\IndicateurImpactController::delete' => '?',
            'App\\Controller\\IndicateurImpactController::edit' => '?',
            'App\\Controller\\IndicateurImpactController::index' => '?',
            'App\\Controller\\IndicateurImpactController::new' => '?',
            'App\\Controller\\IndicateurImpactController::show' => '?',
            'App\\Controller\\MapController::index' => '?',
            'App\\Controller\\QRDashboardController::index' => '?',
            'App\\Controller\\QRScanController::track' => '?',
            'App\\Controller\\ZonePollueeController::batchQR' => '?',
            'App\\Controller\\ZonePollueeController::delete' => '?',
            'App\\Controller\\ZonePollueeController::downloadQRPNG' => '?',
            'App\\Controller\\ZonePollueeController::edit' => '?',
            'App\\Controller\\ZonePollueeController::index' => '?',
            'App\\Controller\\ZonePollueeController::new' => '?',
            'App\\Controller\\ZonePollueeController::show' => '?',
            'App\\Controller\\ZonePollueeController::showQR' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin6Controller:dashboard' => '?',
            'App\\Controller\\ApiController:zones' => '?',
            'App\\Controller\\DashboardIntelligentController:compareZones' => '?',
            'App\\Controller\\DashboardIntelligentController:index' => '?',
            'App\\Controller\\IndicateurImpactController:delete' => '?',
            'App\\Controller\\IndicateurImpactController:edit' => '?',
            'App\\Controller\\IndicateurImpactController:index' => '?',
            'App\\Controller\\IndicateurImpactController:new' => '?',
            'App\\Controller\\IndicateurImpactController:show' => '?',
            'App\\Controller\\MapController:index' => '?',
            'App\\Controller\\QRDashboardController:index' => '?',
            'App\\Controller\\QRScanController:track' => '?',
            'App\\Controller\\ZonePollueeController:batchQR' => '?',
            'App\\Controller\\ZonePollueeController:delete' => '?',
            'App\\Controller\\ZonePollueeController:downloadQRPNG' => '?',
            'App\\Controller\\ZonePollueeController:edit' => '?',
            'App\\Controller\\ZonePollueeController:index' => '?',
            'App\\Controller\\ZonePollueeController:new' => '?',
            'App\\Controller\\ZonePollueeController:show' => '?',
            'App\\Controller\\ZonePollueeController:showQR' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.98k5Ish'])) {
            return $container->privates['.service_locator.98k5Ish'];
        }

        return $container->privates['.service_locator.98k5Ish'] = $instance;
    }
}
