<?php

namespace ContainerHAyQvpA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OluOONXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OluOONX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OluOONX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'indicateurRepo' => ['privates', 'App\\Repository\\IndicateurImpactRepository', 'getIndicateurImpactRepositoryService', true],
            'zoneRepo' => ['privates', 'App\\Repository\\ZonePollueeRepository', 'getZonePollueeRepositoryService', true],
        ], [
            'indicateurRepo' => 'App\\Repository\\IndicateurImpactRepository',
            'zoneRepo' => 'App\\Repository\\ZonePollueeRepository',
        ]);
    }
}
