<?php

namespace ContainerMuZJyUO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KdIY5SBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kdIY5SB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'zone' => ['privates', '.errored..service_locator.kdIY5SB.App\\Entity\\ZonePolluee', NULL, 'Cannot autowire service ".service_locator.kdIY5SB": it needs an instance of "App\\Entity\\ZonePolluee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'zone' => 'App\\Entity\\ZonePolluee',
        ]);

        if (isset($container->privates['.service_locator.kdIY5SB'])) {
            return $container->privates['.service_locator.kdIY5SB'];
        }

        return $container->privates['.service_locator.kdIY5SB'] = $instance;
    }
}
