<?php

namespace ContainerMuZJyUO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dcaf6uTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dcaf6uT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dcaf6uT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qrService' => ['privates', 'App\\Service\\QRCodeService', 'getQRCodeServiceService', true],
            'repository' => ['privates', 'App\\Repository\\ZonePollueeRepository', 'getZonePollueeRepositoryService', true],
        ], [
            'qrService' => 'App\\Service\\QRCodeService',
            'repository' => 'App\\Repository\\ZonePollueeRepository',
        ]);
    }
}
