<?php

namespace ContainerDCm0pbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwHtLwHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TwHtLwH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TwHtLwH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qrService' => ['privates', 'App\\Service\\QRCodeService', 'getQRCodeServiceService', true],
            'zone' => ['privates', '.errored..service_locator.TwHtLwH.App\\Entity\\ZonePolluee', NULL, 'Cannot autowire service ".service_locator.TwHtLwH": it needs an instance of "App\\Entity\\ZonePolluee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'qrService' => 'App\\Service\\QRCodeService',
            'zone' => 'App\\Entity\\ZonePolluee',
        ]);
    }
}
