<?php

namespace ContainerDCm0pbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1RPxoiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1RPxoi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1RPxoi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'scanRepository' => ['privates', 'App\\Repository\\QRScanRepository', 'getQRScanRepositoryService', true],
            'zoneRepository' => ['privates', 'App\\Repository\\ZonePollueeRepository', 'getZonePollueeRepositoryService', true],
        ], [
            'scanRepository' => 'App\\Repository\\QRScanRepository',
            'zoneRepository' => 'App\\Repository\\ZonePollueeRepository',
        ]);
    }
}
