<?php

namespace ContainerDCm0pbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndicateurImpactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cP0vxgj.App\Entity\IndicateurImpact' shared service.
     *
     * @return \App\Entity\IndicateurImpact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cP0vxgj": it needs an instance of "App\\Entity\\IndicateurImpact" but this type has been excluded in "config/services.yaml".');
    }
}
