<?php

namespace ContainerDCm0pbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUxMap_RendererFactory_LeafletService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux_map.renderer_factory.leaflet' shared service.
     *
     * @return \Symfony\UX\Map\Bridge\Leaflet\Renderer\LeafletRendererFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-map'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'AbstractRendererFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-map'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'RendererFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-leaflet-map'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'LeafletRendererFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-map'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Icon'.\DIRECTORY_SEPARATOR.'UxIconRenderer.php';

        $a = ($container->privates['stimulus.helper'] ?? self::getStimulus_HelperService($container));

        if (isset($container->privates['ux_map.renderer_factory.leaflet'])) {
            return $container->privates['ux_map.renderer_factory.leaflet'];
        }

        $instance = new \Symfony\UX\Map\Bridge\Leaflet\Renderer\LeafletRendererFactory($a, new \Symfony\UX\Map\Icon\UxIconRenderer(NULL));

        if (isset($container->privates['ux_map.renderer_factory.leaflet'])) {
            return $container->privates['ux_map.renderer_factory.leaflet'];
        }

        return $container->privates['ux_map.renderer_factory.leaflet'] = $instance;
    }
}
