<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IndicateurImpact extends \App\Entity\IndicateurImpact implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'co2Evite' => [parent::class, 'co2Evite', null, 16],
        "\0".parent::class."\0".'dateCalcul' => [parent::class, 'dateCalcul', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'totalKgRecoltes' => [parent::class, 'totalKgRecoltes', null, 16],
        "\0".parent::class."\0".'zonePolluees' => [parent::class, 'zonePolluees', null, 16],
        'co2Evite' => [parent::class, 'co2Evite', null, 16],
        'dateCalcul' => [parent::class, 'dateCalcul', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'totalKgRecoltes' => [parent::class, 'totalKgRecoltes', null, 16],
        'zonePolluees' => [parent::class, 'zonePolluees', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
