<?php

namespace ContainerHR3X1Pc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FALByUnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fALByUn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'indicateur' => ['privates', '.errored..service_locator.fALByUn.App\\Entity\\IndicateurImpact', NULL, 'Cannot autowire service ".service_locator.fALByUn": it needs an instance of "App\\Entity\\IndicateurImpact" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'indicateur' => 'App\\Entity\\IndicateurImpact',
        ]);

        if (isset($container->privates['.service_locator.fALByUn'])) {
            return $container->privates['.service_locator.fALByUn'];
        }

        return $container->privates['.service_locator.fALByUn'] = $instance;
    }
}
