<?php

namespace ContainerHR3X1Pc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CP0vxgjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cP0vxgj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cP0vxgj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'indicateur' => ['privates', '.errored..service_locator.cP0vxgj.App\\Entity\\IndicateurImpact', NULL, 'Cannot autowire service ".service_locator.cP0vxgj": it needs an instance of "App\\Entity\\IndicateurImpact" but this type has been excluded in "config/services.yaml".'],
        ], [
            'indicateur' => 'App\\Entity\\IndicateurImpact',
        ]);
    }
}
