<?php

namespace ContainerHR3X1Pc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZonePolluee2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kdIY5SB.App\Entity\ZonePolluee' shared service.
     *
     * @return \App\Entity\ZonePolluee
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kdIY5SB": it needs an instance of "App\\Entity\\ZonePolluee" but this type has been excluded in "config/services.yaml".');
    }
}
