<?php

namespace ContainerMzXLClB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LioYYHKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LioYYHK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin6Controller::dashboard' => ['privates', '.service_locator.n_IEkrD', 'get_ServiceLocator_NIEkrDService', true],
            'App\\Controller\\IndicateurImpactController::delete' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController::edit' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController::index' => ['privates', '.service_locator.qAlMOrK', 'get_ServiceLocator_QAlMOrKService', true],
            'App\\Controller\\IndicateurImpactController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\IndicateurImpactController::show' => ['privates', '.service_locator.cP0vxgj', 'get_ServiceLocator_CP0vxgjService', true],
            'App\\Controller\\ZonePollueeController::delete' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController::edit' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController::index' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\ZonePollueeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ZonePollueeController::show' => ['privates', '.service_locator.R2zCFxk', 'get_ServiceLocator_R2zCFxkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin6Controller:dashboard' => ['privates', '.service_locator.n_IEkrD', 'get_ServiceLocator_NIEkrDService', true],
            'App\\Controller\\IndicateurImpactController:delete' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController:edit' => ['privates', '.service_locator.fALByUn', 'get_ServiceLocator_FALByUnService', true],
            'App\\Controller\\IndicateurImpactController:index' => ['privates', '.service_locator.qAlMOrK', 'get_ServiceLocator_QAlMOrKService', true],
            'App\\Controller\\IndicateurImpactController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\IndicateurImpactController:show' => ['privates', '.service_locator.cP0vxgj', 'get_ServiceLocator_CP0vxgjService', true],
            'App\\Controller\\ZonePollueeController:delete' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController:edit' => ['privates', '.service_locator.kdIY5SB', 'get_ServiceLocator_KdIY5SBService', true],
            'App\\Controller\\ZonePollueeController:index' => ['privates', '.service_locator.DDaIjT0', 'get_ServiceLocator_DDaIjT0Service', true],
            'App\\Controller\\ZonePollueeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ZonePollueeController:show' => ['privates', '.service_locator.R2zCFxk', 'get_ServiceLocator_R2zCFxkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin6Controller::dashboard' => '?',
            'App\\Controller\\IndicateurImpactController::delete' => '?',
            'App\\Controller\\IndicateurImpactController::edit' => '?',
            'App\\Controller\\IndicateurImpactController::index' => '?',
            'App\\Controller\\IndicateurImpactController::new' => '?',
            'App\\Controller\\IndicateurImpactController::show' => '?',
            'App\\Controller\\ZonePollueeController::delete' => '?',
            'App\\Controller\\ZonePollueeController::edit' => '?',
            'App\\Controller\\ZonePollueeController::index' => '?',
            'App\\Controller\\ZonePollueeController::new' => '?',
            'App\\Controller\\ZonePollueeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin6Controller:dashboard' => '?',
            'App\\Controller\\IndicateurImpactController:delete' => '?',
            'App\\Controller\\IndicateurImpactController:edit' => '?',
            'App\\Controller\\IndicateurImpactController:index' => '?',
            'App\\Controller\\IndicateurImpactController:new' => '?',
            'App\\Controller\\IndicateurImpactController:show' => '?',
            'App\\Controller\\ZonePollueeController:delete' => '?',
            'App\\Controller\\ZonePollueeController:edit' => '?',
            'App\\Controller\\ZonePollueeController:index' => '?',
            'App\\Controller\\ZonePollueeController:new' => '?',
            'App\\Controller\\ZonePollueeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.LioYYHK'])) {
            return $container->privates['.service_locator.LioYYHK'];
        }

        return $container->privates['.service_locator.LioYYHK'] = $instance;
    }
}
