<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCm0pbS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCm0pbS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCm0pbS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCm0pbS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDCm0pbS\App_KernelDevDebugContainer([
    'container.build_hash' => 'DCm0pbS',
    'container.build_id' => '79ee3c91',
    'container.build_time' => 1771972626,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCm0pbS');
