<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMuZJyUO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMuZJyUO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMuZJyUO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMuZJyUO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMuZJyUO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MuZJyUO',
    'container.build_id' => '7a11688e',
    'container.build_time' => 1772063240,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMuZJyUO');
