<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFaF24Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFaF24Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFaF24Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFaF24Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFaF24Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFaF24Z',
    'container.build_id' => 'e02e8577',
    'container.build_time' => 1771797547,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFaF24Z');
