<?php

namespace ContainerHFaF24Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NIEkrDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n_IEkrD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n_IEkrD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'indicateurRepository' => ['privates', 'App\\Repository\\IndicateurImpactRepository', 'getIndicateurImpactRepositoryService', true],
            'zoneRepository' => ['privates', 'App\\Repository\\ZonePollueeRepository', 'getZonePollueeRepositoryService', true],
        ], [
            'indicateurRepository' => 'App\\Repository\\IndicateurImpactRepository',
            'zoneRepository' => 'App\\Repository\\ZonePollueeRepository',
        ]);
    }
}
