<?php

namespace ContainerHFaF24Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R2zCFxkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R2zCFxk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R2zCFxk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zone' => ['privates', '.errored..service_locator.R2zCFxk.App\\Entity\\ZonePolluee', NULL, 'Cannot autowire service ".service_locator.R2zCFxk": it needs an instance of "App\\Entity\\ZonePolluee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'zone' => 'App\\Entity\\ZonePolluee',
        ]);
    }
}
